apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-api-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/whitelist-source-range: "94.247.130.46/32"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - storage-api.imas.kz
      secretName: imas-tls
  rules:
    - host: "storage-api.imas.kz"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: storage-api-service
              port:
                number: 8000