apiVersion: v1
kind: Service
metadata:
  name: storage-api-service
  namespace: production
spec:
  selector:
    app.kubernetes.io/name: storage-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000